version: '3.8'

services:
  matching-service-rabbitmq:
    restart: on-failure
    build: 
      context: ./services/matching-service-rabbitmq
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/matching-service-rabbitmq:/app
    depends_on:
      - rabbitmq
    environment:
      - PORT=6001
      - RABBITMQ_URL=amqp://rabbitmq
    ports:
      - '6001:6001'

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - '15672:15672'  # Management Console
      - '5672:5672'    # RabbitMQ service
