# docker-compose.yml
version: '3.8'
services:
  web:
  
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '6543:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local