# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - DATABASE_URL="postgres://postgres:postgres@localhost:6543/mydb?schema=public"
    ports:
      - '6543:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local