# docker-compose.yml
version: '3.8'
services:
  # backend:
  #   build: .
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres@db:5432/user-service?schema=public
  #     - SERVER_PORT=2000
  #   ports:
  #     - '2000:2000'
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '6543:5432'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user-service
  test_db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '6542:5433'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test-user-service
volumes:
  db:
    driver: local
  test_db:
    driver: local