# docker-compose.yml
version: '3.8'
services:
  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:6543/mydb?schema=public
      - SERVER_PORT=2000
    ports:
      - '2000:2000'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '6543:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local