# docker-compose.yml
version: '3.8'
services:
  backend:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/user-service?schema=public
      - SERVER_PORT=2000
    ports:
      - '2000:2000'
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user-service
volumes:
  db:
    driver: local