#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

SERVICES="frontend matching-service-rabbitmq"

for package in $SERVICES; do
  echo "Linting $package..."
  (cd services/$package && npm run lint:fix)
done
